env:
  global:
    - secure: Gi1/yYnWXfkqUqFDxivo63ebfBkW6IRjuBe41I6VGDx+MVr4tQ8nPZYSGWwVqAX5smx4sj7t8vxVBQ9E4FY/iMFGg2bRo5GrSMDEY0RE6kvZg22eMrinsZqgX7SE3Cyl3R0fQq8auG6BaDerQ5a7asycQyQPLbJFr3Jl6jlTx41REe7CXqDYUQT0OETyAlDR2oqa+jjhChgN1s71FfnByAojwfBpHtF/qHym8tao78v6UKRVQWIvlA3yWIx+tZFnVrzuEup3lkGOIN3sY1vod7U+ZnGykLO04rGbTTmuiMQY1dwFh+lLOZfqjXLPoyrJxxz5CWa8dnD91/fm7YBp+f9dE6qwMUHzgQ8DT2b/KQbG5D8bxt8RTKix8G53enZj9H4JQ7uV+UCIYXeyxDM65IcPM+Bnjp7DdgBBTba4Bvv773VoT0n510wYH/zRb5DZ5Ii0OAjl3cRMpcM5nq7Wxfa6yERPBz3xzZ9/ZDH65GDs+RIWs+2n8eTu+EHObdg5a3BJ8hsKopUamsKynhpoDlEEHOnpvih6Z3iGkHu3GczciuWW3n4zhewWQebqVTlLhrEuMXJhfRIhq2sKI6Yh1AWYvmcAj2Db0UrcmiBmiiLq3wInQVZ2n1ehjMUaagoqcb11rDJpKPbVHbVW+PFQ2ZZA5sZWIl6JyXrri4B6ScU=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/DShield.org-Suspicious-Domain-List
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
