env:
  global:
    - secure: YIPFq2ewMvkc5t3l7Wb3wIuVNOOyisAhVfDiSVmRDq7CbLfkF2Z8OuK2rlJ8rO883PCOqvV9mRmEeJXhyez9kO4ceHMvwmaBmgQjd599GflOclCsksBVkq/uRYCAuNRiGI36iVu4nsBZrpFI1LS20bF1b6fmFzSqsZck3dKUUEIzm76C0wND5IdA/yI8dl5j6DBbuQ3vw5sY3EI6spcoMallPWFCvMgQpFyrTCziqEVtsnfGa3yLYNw1EQWAciBoVAe1bLBe6fep8SUratvmUuGsyMS3wTTm4OvSYaP6t9mxlLswRc9geimCOGQ0uw8O07nBVDPSc6G4v8rprv04Bc1aBY+wZitlUqSBQZtgJblrwWBfc6gDBjv6bYmYdNqEt7ekLRRKRtTwQt4VYx6U3Tc6QrNEh2HwXCXpKmdu0Ey0alw4qk98/Wr050j4KgIqmyiWuMhtid1dDz6qjLYi/wYdYUC/RhHuUv6pCcvRBxk7nV7y0N9iszlvF2J6+D9N+PwMiyeKssKwf2UoHj0g25oPESfXZ6tAlGeF2+UM0gtEHtBm/GnaNEdm7EwNvCAFse7JZkTF+hEUfO6ekTwiKaL3be6B/ElZfL7kOCc4rUcj4XlHLbUJH+F9mU20At8e8CbEzYQ7btRVHa0uA8LEq3MmdsiF0ICtgI4DlCKM/A4=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/DShield.org-Suspicious-Domain-List
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
