env:
  global:
    - secure: QpcxSuj31+q2BgwPBLCPHc9CZDeI1Mdx256Vok2RGrZpGZ5IgMJArjXSjPRWqQwbpUoxf0Bha9yJ578rL00Tr0ZTjtF+p7ISY9/lEozE2bb5sVtOZ91QPtyZwnAPWE3BRByxogveCQ4mMilIhQRvjM2t6CWBSQsJaCLn37Ap2IQ5IM5BrD8WVxUfmgzL5riTuzF9h8q++whQLqIfbfDq/UzWnnONdETK0K1U1KEJc01t3nv0w+9Msm5MCac03WzJegTGfZF9dmDr8zXtp3e8skuq1p7pks2GtJm/svb35cV/Fq08wQr11oSsP11BNGkLO9y+DQVpRn62RpWlEQ69dR4yMedSeIKNX2DFNdApit9xkcLCqAPK4IqAN+090vcC5vFg+8rbQrC1iXIuZpGOX+FZy3LSLX4slR2JCu3Mq0TTtx2tGnqACLxkkTHUEZQ2yAOK9JeytEW8nKB2T2LEUGLa+YngZ76/wjTNxGAD8uw20Jf2tdxaU6S/auilQghUbZ5GAtptOFhxUyV8KYq3P5bJrOdX2OgtmlA2IZ6AYheFU84GKoUbN+Fam5D+AMdRPVXWKgWNApui1pIxYyMIKss4LwqaXnVkLWbj2899o1F9yjz5J/gkMfNtpI0SSyI+I5nzABWYi4AIFCHJSNbB0f+JcL8MmK4+txteSDhNP8k=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/DShield.org-Suspicious-Domain-List
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
