env:
  global:
    - secure: B6JrEbhJzDW2yUq/050R14+WsWVedeZ2X9S/UeuhxCJhWHGaI4Lw3ZjJ1mjOnHd08mMXZBaGkad5atDann/4zfsZMG80ksJVGeSZiWyvshCgdcP0ppJGnr6ZCDDuswaTU/Ax4UZ+Jb2/AT/ybdC1g2uI8bDNdo6ALYxj7XX6qfNRQPOfCp72orcp4TomZHMX5VyUa2blzwJpMDgIZ8ZuKz2GbKyInwlFPuC7ybDZ55WmDYquJvpwW8mJ9BaiCDUmYclR8W8FTCne5pld2CFnr4Yv0cq4Wp07WmcpQM6tLb9BW8F/fA3DjbwDC5NzMwHZ+qrvSGFLu2Ob7gZAx69L2VuFn0Pjp4IJnwPhToo94GjypG9arkYZIseUhjKl+AolF8CvnKuHjMzpGvJHRhjYW8cAusAtqssorxreX/GKI05DKn6Cop0WuO8QbyyREhE8OgmObDmUOcr0sWYq29c+ak5Dmd7YrF814TMT+XNElOdB/DFOw4VKK9vxOP96LAycKLGRWM52KCqLoR2kZuronKtlpApFpecdJQf/xvIkqJ9xwDhkGmMfFOu96AjXlP4akoA3HliSttGyL72wb6npBAqnOXmQjWae+qNwfxe+qQZ+nIu8hN5CoOA3m3RHs0tJWO5UdAVSISNvfYtIV/d9N2irfUHqfF8tILZn7kKKDi8=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/DShield.org-Suspicious-Domain-List
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
