env:
  global:
    - secure: DQdvNLDgtey54H40ydtVtIuE+rks0m8BBMiVMCTb4tcYxD1qGTYlo3psL2xrqoPHlutHDTyL0J9PGX0hPkccq0TqbNnTVklJxVILsn8+MGFsiNRN9GtKtvMj2cl+3k/4zTu06ckSWhz0GCFCL4hpJ4iXD8VjVR9bBC1JbI/TqI0ILrHFZuKmMKK5C3q0clKGvAxKGdTLSVri6Wbk5TMHaTlOcBXiNTEsmx1YGQ1Ic++RXDekm22ATgCGAgqkQhndAJYqcP44+UZEdj+oU+oUR1AnevfK5mMkKfjvPZA5shdnl+RjKnc8Wr888VZ9DpAzPZMxVh08cveoBO2x5oIU8FlIJgwcbRA5Y56Fny30v0WR7KnXXA5w2tEAxzX5yTJLTpPAEe0/MrlnkDDrkfMLgFc9aBXRvrXjpvsnMM2Kdqy0edRAy19T5owwaaeY8p+X1Hia1w7LJZEoVO+1IeAhC2olHzzuEpkHWfoN0VAIZXGCnlvJGN8qreixCwaEXoNqnV4B63PF1MRYyxWwn0kLK/jQ2XwqDd8Mm/E3ZUzvtelS8iygLFnAs47Lzj4kRjgCdiP+8fBs2p3g1RkdGMvhfEghh/FKHJ91/5cvMQbPGEd+Ior1qo/R8x/ZWJhgDKJujLMyRgK9TQZXuhYST5G8MnMl4PVTx0PO3yQzsFsEpLU=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/DShield.org-Suspicious-Domain-List
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
