env:
  global:
    - secure: 08PHP6VZKWTgqAZfjDunF4nkfayzoGh/D3RUiEL2Xnm5AD8aSNcYbrD78J9EaKJznuc1XB6xlMAhSG9EgpLHRwFn0O7PQ0vHtyyq3kVv9qXyT/g7jD8p9ZJ9rxm2kkPjAHd9eIjcm5I9aX+qaF6ozq13GjHyQDRP1p/ee/psidouqG6ub0rzawbDr3AiYsTNoPRE6/DQ1lRrNKmTpAs7C1EjxI9+Gu20Kj8pksbpWEUyKi5PBoSthniPRgx6pxmHHKNVzqyRdCiwNzPO4J1XUqURlUvcSkyKWqlcFUaNMV5k2nBhr859kTNcD1pxudYMzw2XwTmYAk8OR6ul6Twh6JlG6/ynorvgwp0Ra9rqIQf83py/RtdwO6cA9TRp2xn+RyQm1hqUfJST2KMv25NmkepEUVwhYnyjQwUyd6DNdaxATthGbtuIv9QKOaTFZWMDH1hpcuXxQ/7Fhl8k4zuvar/UulwzkN6hR8CThTKLcbDxVxTwxXC7/LuJtBrDyngCI+VLLRjXQXtHOtx41WyLA+HymB3sJvtZMOv0tfMgv/FeoO7D70RwgnlMdEprL/YIe0+hxmdTNy0FeNr7UDmUELvCoSYfcVSm8X/jjCPxvVWu3mUEdeM1q5xmU3VYGewizVuJgs2uYdlARpWNCU5cELewtlv8djSF/AS4TXns+6w=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/DShield.org-Suspicious-Domain-List
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
